### ISSUE TITLE
Why is a wrapper needed for clicked functions?

### ISSUE THREAD

**Issue by auszone** [ripexz/python-tkinter-minesweeper#2]
As title, I tried to remove the wrapper but it somehow crashed. Why is that?

**Comment by ripexz** [comment]
If I recall correctly you need to wrap them in anonymous functions  (via lambda) to be able to pass arguments.

This was made when I was learning Python, which I admit I barely used in the last two years, so the code isn't top notch. :smile:

**Comment by auszone** [comment]
I changed it from
```
self.buttons[x][0].bind('<Button-1>', self.lclicked_wrapper(x))
```
to
```
self.buttons[x][0].bind('<Button-1>', self.lclicked(self.buttons[x]))
```
it just popped out "You Lose" window and here's my trackback.
```
Traceback (most recent call last):
  File "minesweeper.py", line 221, in <module>
    main()
  File "minesweeper.py", line 216, in main
    minesweeper = Minesweeper(root)
  File "minesweeper.py", line 61, in __init__
    self.buttons[x][0].bind('<Button-1>', self.lclicked(self.buttons[x]))
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk/Tkinter.py", line 1089, in bind
    return self._bind(('bind', self._w), sequence, func, add)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk/Tkinter.py", line 1047, in _bind
    return self.tk.call(what + (sequence,))
_tkinter.TclError: can't invoke "bind" command:  application has been destroyed
```

**Comment by ripexz** [comment]
You'll still need lambda, even if you don't separate the function out. Try this:

```
self.buttons[x][0].bind('<Button-1>', lambda Button, pos = x: self.lclicked(self.buttons[pos]))
```

**Comment by auszone** [comment]
That's where my question is, because it does not have to be lambda to pass a function as an argument. Lambda is just a syntax-sugar to me.

**Comment by auszone** [comment]
Is that possible that it's because it's in init function, so it has to be a lambda?

**Comment by ripexz** [comment]
I dunno, don't have the time to play around with it right now, give it a go yourself. :smile: 
If it's just syntactic sugar and not necessary then I'm looking forward to your PR :wink:

**Comment by auszone** [comment]
Haha ok! Truly appreciate your time and effort. :)
